version: '2'
services:
  deploy:
    build: ./
    working_dir: /deployer/ansible
    volumes:
      - ".:/deployer"
    environment:
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}