---
  - name: Deploy API - API Gateway, Application Lambda
    cloudformation:
      stack_name: "{{application}}-{{env}}-api"
      state: present
      region: "{{aws_region}}"
      disable_rollback: true
      template: "cloudformation/api.yml"
      stack_policy: "cloudformation/allow_update_policy.json"
      template_parameters:
        AppplicationName: "{{application_name}}"
      tags:
        project: "{{project}}"
        application: "{{application}}"
        environment: "{{env}}"
